language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
# setup the main DIRAC repo
  - git clone -b rel-v6r17 https://github.com/DIRACGrid/DIRAC ../DIRAC
# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - echo $PYTHONPATH
  - py.test
after_success:
  - coveralls
